# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='料理名')),
                ('Price', models.IntegerField(blank=True, verbose_name='価格')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=255, verbose_name='店名')),
                ('Address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('Open', models.CharField(blank=True, max_length=255, verbose_name='オープン日')),
                ('Category', models.CharField(blank=True, max_length=255, verbose_name='カテゴリ')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Shop', verbose_name='店舗'),
        ),
    ]
