# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20171014_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Open',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='ShopName',
            new_name='shopname',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ShopName',
        ),
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Shop', to='cms.Shop', verbose_name='店舗'),
        ),
    ]
