# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20171014_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='shop',
        ),
    ]
