# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_food_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=19, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=19, verbose_name='経度'),
        ),
    ]
