# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20171016_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.CharField(default=0, max_length=255, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.CharField(default=0, max_length=255, verbose_name='経度'),
        ),
    ]
