# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20171016_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='cms.Shop', verbose_name='店舗'),
        ),
    ]
