# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20171212_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='open',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopname',
        ),
    ]
