# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20171212_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='料理名'),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(blank=True, default=1, verbose_name='価格'),
        ),
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='cms.Shop', verbose_name='店舗'),
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.CharField(default=0, max_length=255, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.CharField(default=0, max_length=255, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open',
            field=models.CharField(blank=True, max_length=255, verbose_name='オープン日'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopname',
            field=models.CharField(default=1, max_length=255, verbose_name='店名'),
        ),
    ]
