# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20171212_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='open_val',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='rate',
        ),
    ]
