# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_shop_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open_val',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='rate',
            field=models.CharField(default=0, max_length=255, verbose_name='評価'),
        ),
    ]
