# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_remove_shop_open_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open_val',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
