# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_shop_open_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shopname',
        ),
    ]
