# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20171219_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='popular_val',
            field=models.CharField(blank=True, default=1, max_length=255),
        ),
    ]
