# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_food_popular_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='popular_val',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
