# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20171220_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='url',
            field=models.CharField(default='test', max_length=2000, verbose_name='url'),
        ),
    ]
